### ISSUE TITLE
 No module named 'carla.driving_benchmark'

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/reinforcement-learning#20]
When I run python run_RL.py on windows10, an error occurs:
ModuleNotFoundError: No module named 'carla.driving_benchmark'
Does anyone know how to solve it ?

**Comment by d34dl0ckk** [comment]
You just need to copy the carla folder in your working directory. Hope this helps!

**Comment by Fangwq** [comment]
@AminaBa, I have the same problem, and I test the code on 0.9.10.1. Could you explain it in detail? Thank you very much!

**Comment by EchoYJJ** [comment]
> @Aminaba, I have the same problem, and I test the code on 0.9.10.1. Could you explain it in detail? Thank you very much!

@4mina @Fangwq Do you have any solutions?Thanks.

**Comment by HappyDay-design** [comment]
> > @Aminaba, I have the same problem, and I test the code on 0.9.10.1. Could you explain it in detail? Thank you very much!
> 
> @4mina @Fangwq Do you have any solutions?Thanks.

you copy folder carla in Carla 0.8.2 to your working directory. In this folder it has driving_benchmark folder. 

![image](https://user-images.githubusercontent.com/82990411/135613732-8ff3a396-5488-47d3-b8bc-014e5e790d91.png)
